function applyTheme(t){state.theme=t;document.documentElement.classList.toggle("dark",t==="dark");localStorage.setItem("al_theme",t);const i=document.getElementById("themeIcon");if(i)i.className=t==="dark"?"fas fa-sun text-lg":"fas fa-moon text-lg";const f=document.getElementById("dynamicFavicon");if(f)f.href=t==="dark"?"logo2.png":"logo.png";}
function toggleTheme(){applyTheme(state.theme==="dark"?"light":"dark");}
function showToast(m,t="info"){const c=document.getElementById("toastContainer"),ic={info:"fa-info-circle",success:"fa-check-circle",error:"fa-exclamation-circle",warning:"fa-exclamation-triangle"},co={info:"var(--accent)",success:"#10b981",error:"#ef4444",warning:"#f59e0b"},e=document.createElement("div");e.className="toast";e.innerHTML=`<i class="fas ${ic[t]}" style="color:${co[t]}"></i><span>${m}</span>`;c.appendChild(e);setTimeout(()=>{e.style.animation="slideOut .3s ease forwards";setTimeout(()=>e.remove(),300);},3000);}
function generateId(){return"n"+Date.now().toString(36)+Math.random().toString(36).substr(2,5);}
function escapeHtml(s){const d=document.createElement("div");d.textContent=s;return d.innerHTML;}
function escapeAttr(s){return(s||"").replace(/"/g,"&quot;").replace(/'/g,"&#39;");}
function renderLatexText(t){t=t.replace(/\\\[([\s\S]*?)\\\]/g,(m,l)=>{try{return katex.renderToString(l.trim(),{displayMode:true,throwOnError:false});}catch(e){return m;}});t=t.replace(/\\\(([\s\S]*?)\\\)/g,(m,l)=>{try{return katex.renderToString(l.trim(),{displayMode:false,throwOnError:false});}catch(e){return m;}});return t;}
function updateUserUI(){const u=state.user;document.getElementById("sidebarAvatar").textContent=u?u.avatar:"?";document.getElementById("sidebarName").textContent=u?u.name:"Guest";document.getElementById("sidebarEmail").textContent=u?u.email:"Sign in to get started";document.getElementById("headerAuthBtn").style.display=u?"none":"flex";document.getElementById("logoutIcon").style.display=u?"":"none";}
function timeAgo(d){const s=Math.floor((Date.now()-new Date(d).getTime())/1000);if(s<60)return "just now";if(s<3600)return Math.floor(s/60)+"m ago";if(s<86400)return Math.floor(s/3600)+"h ago";return Math.floor(s/86400)+"d ago";}
function updateNotifBadge(){const b=document.getElementById("notifBadge"),c=state.notifications.filter(n=>!n.read).length;if(!b)return;b.textContent=c>9?"9+":c;b.style.display=c>0?"flex":"none";c>0?b.classList.add("visible"):b.classList.remove("visible");}
function renderNotifDropdown(){const l=document.getElementById("notifList");if(!l)return;if(!state.notifications.length){l.innerHTML='<p class="text-sm text-center py-6" style="color:var(--text2)">No notifications yet</p>';return;}const ic={success:"fa-check-circle",info:"fa-info-circle",warning:"fa-exclamation-triangle",error:"fa-times-circle"};l.innerHTML=state.notifications.slice(0,20).map(n=>`<div class="notif-item ${n.read?'':'unread'}"><div class="notif-icon ${n.type||'info'}"><i class="fas ${ic[n.type]||ic.info}"></i></div><div class="notif-body"><div class="notif-message">${n.message||''}</div><div class="notif-time">${timeAgo(n.createdAt||n.timestamp)}</div></div></div>`).join("");}
function toggleNotifDropdown(){state.notifOpen=!state.notifOpen;const d=document.getElementById("notifDropdown");if(state.notifOpen){renderNotifDropdown();d.classList.add("open");}else{d.classList.remove("open");}}
async function markAllNotifsRead(){state.notifications.forEach(n=>n.read=true);updateNotifBadge();renderNotifDropdown();if(state.uid)markAllNotifsReadDb();}
